<p>Static Text</p>
<?php
/**
 * Created by PhpStorm.
 * User: MD. Fakhruddin Gazzali
 * Date: 13-Nov-18
 * Time: 9:27 PM
 */
echo "<p> This text is generated by PHP !</p>";
?>
<p>While this was not</p>

<?php
$myName = "Gazzali";
$friendsName = "Tarik";
$age = 14;
echo "<p>My name is $myName & my friend's name is $friendsName. My age is $age</p>";
?>

<?php
$title = "Test Title";
$content = "<h1>Test page with full PHP</h1>";
$page = "<!DOCTYPE html> 
         <html>
         <head>
         <title>$title</title>
         <meta http-equiv='Content-Type' content='test/html; charset=utf-8'/>
         </head>
         <body>
         $content
         </body>
         </html>";
echo $page;